### ISSUE TITLE
Build Failure - RNGaidPackage.java:26: error

### ISSUE THREAD

**Issue by ghost** [applike/react-native-advertising-id#1]
Hey mates, getting the following error when trying to react-native run-android;
..\node_modules\react-native-gaid\android\src\main\java\com\mobvantage\react\gaid\RNGaidPackage.java:26: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

Pretty new to React Native, any ideas on how to go about fixing this error?

**Comment by FlorianBergmann** [comment]
Hey there, what version of React Native are you using? If it is an older version than you will have to update to a more recent version in order to use the library.

**Comment by FlorianBergmann** [comment]
Closed due to inactivity
