### ISSUE TITLE
Doesn't work with iOS

### ISSUE THREAD

**Issue by hmvs** [applike/react-native-advertising-id#18]
Package: 1.0.11
RN: 0.61.5

When I use automatic: `react-native link react-native-advertising-id` and `pod install` it has errors that `swift version` is not specified in `podspec`.

When I follow manual instructions I've got these errors: 
`/testapp/node_modules/react-native-advertising-id/ios/RNAdvertisingId-Bridging-Header.h:1:9: 'React/RCTBridgeModule.h' file not found`.

I've googled this error and tried to disable Parallelized build.  It didn't help.

Quick help is very appreciated and can be financially rewarded.  Automatic link is the best option.

**Comment by mtebele** [comment]
@hmvs how did you solve it?

**Comment by rizkiandrianto** [comment]
@mtebele @hmvs did you guys already solve it?
